[program:mottzi]
command=/var/www/mottzi/deploy/Mottzi serve --env development
directory=/var/www/mottzi/
user=root
redirect_stderr=true
stdout_logfile=/var/www/mottzi/deploy/Mottzi.log

; Auto-Restart:
autorestart=true       ; Always restart, regardless of exit code
startretries=1000000   ; Retry indefinitely (prevents Supervisor from giving up)
exitcodes=0            ; Treat exit codes other than 0 as "unexpected" (triggers restart)
startsecs=1            ; Wait 1 second before considering the process "started"