; 1. The Main Application
[program:mottzi]
command=/var/www/mottzi/deploy/Mottzi serve --env development --port 8080
directory=/var/www/mottzi/
user=root
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/www/mottzi/deploy/Mottzi.log
exitcodes=0            ; Treat exit codes other than 0 as "unexpected" (triggers restart)
startsecs=1            ; Wait 1 second before considering the process "started"

; 2. The Deployer Service
[program:deployer]
command=/var/www/mottzi/deploy/Deployer serve --env development --port 8081
directory=/var/www/mottzi/
user=root
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/www/mottzi/deploy/Deployer.log
exitcodes=0            ; Treat exit codes other than 0 as "unexpected" (triggers restart)
startsecs=1            ; Wait 1 second before considering the process "started"